# -*- coding: utf-8 -*-
"""min 2same 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cNdiWBCkNaua1tC71O9Zk9YEUKEJkmU7
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load the dataset
df = pd.read_csv("pollution_comparison_dataset.csv")

# Quick overview
print(df.head())
print("\nTotal records:", len(df))
print("\nEvent types:", df['Event_Type'].unique())

"""1️⃣ Which Indian state caused the most pollution during Diwali?"""

diwali_df = df[df["Event_Type"] == "Diwali"]

state_pollution = diwali_df.groupby("Location")[["PM2.5_ugm3", "CO2_tonnes"]].mean().sort_values(by="PM2.5_ugm3", ascending=True)

plt.figure(figsize=(8, 4))
sns.barplot(x=state_pollution["PM2.5_ugm3"], y=state_pollution.index, palette="YlOrRd", legend=False)
plt.title("Average PM2.5 Levels During Diwali by State", fontsize=14)
plt.xlabel("Average PM2.5 (µg/m³)", fontsize=12)
plt.ylabel("Indian States", fontsize=12)
plt.grid(axis='x', linestyle='--', alpha=0.6)
plt.tight_layout()
plt.show()

"""2️⃣ Which region in Ukraine had the highest pollution during the war?"""

war_df = df[df["Event_Type"] == "War"]

region_pollution = war_df.groupby("Location")[["PM2.5_ugm3", "CO2_tonnes"]].mean().sort_values(by="PM2.5_ugm3", ascending=False)

print(region_pollution)

plt.figure(figsize=(8,4))
sns.barplot(y=region_pollution.index, x=region_pollution["PM2.5_ugm3"], palette="viridis")
plt.title("Average PM2.5 Levels in Ukraine During War")
plt.ylabel("PM2.5 (µg/m³)")
plt.xlabel("Ukrainian Regions")
plt.xticks(rotation=30)
plt.tight_layout()
plt.show()

"""3️⃣ Compare PM2.5 of Diwali vs War"""

plt.figure(figsize=(8,5))
sns.lineplot(x="Event_Phase", y="PM2.5_ugm3", hue="Event_Type", data=df, palette=["orange","steelblue"])
plt.title("PM2.5 Levels Before, During, and After Each Event")
plt.ylabel("PM2.5 (µg/m³)")
plt.xlabel("Event Phase")
plt.show()

import pandas as pd
import matplotlib.pyplot as plt

co2_comparison = df.groupby("Event_Type")["CO2_tonnes"].mean().sort_values(ascending=True)

plt.figure(figsize=(8,4))
bars = plt.barh(co2_comparison.index, co2_comparison.values, color=["orange","steelblue"])

for bar in bars:
    plt.text(bar.get_width() * 1.02, bar.get_y() + bar.get_height()/2,
             f"{bar.get_width():,.0f} tonnes", va='center', fontsize=10)

plt.title("Average CO₂ Emissions: Diwali vs Russia–Ukraine War", fontsize=13)
plt.xlabel("Average CO₂ Emissions (tonnes, log scale)")
plt.xscale('log')
plt.grid(axis='x', linestyle='--', alpha=0.6)

plt.show()

diwali_df = df[df["Event_Type"] == "Diwali"]
war_df = df[df["Event_Type"] == "War"]

def percent_increase(event_df, pollutant="PM2.5_ugm3"):
    before_avg = event_df[event_df["Event_Phase"]=="Before"][pollutant].mean()
    during_avg = event_df[event_df["Event_Phase"]=="During"][pollutant].mean()
    increase = during_avg - before_avg
    percent = (increase / before_avg) * 100
    return before_avg, during_avg, increase, percent

diwali_percent_pm25 = percent_increase(diwali_df, "PM2.5_ugm3")
war_percent_pm25 = percent_increase(war_df, "PM2.5_ugm3")

diwali_percent_co2 = percent_increase(diwali_df, "CO2_tonnes")
war_percent_co2 = percent_increase(war_df, "CO2_tonnes")

events = ["Diwali", "War"]
pm25_percent = [diwali_percent_pm25, war_percent_pm25]
co2_percent = [diwali_percent_co2, war_percent_co2]

x = np.arange(len(events))
width = 0.35

fig, ax = plt.subplots(figsize=(8,5))
rects1 = ax.barh(x - width/2, pm25_percent, width, label='PM2.5 Increase (%)', color='orange')
rects2 = ax.barh(x + width/2, co2_percent, width, label='CO₂ Increase (%)', color='steelblue')

ax.set_xlabel('Percentage Increase (%)')
ax.set_yticks(x)
ax.set_yticklabels(events)
ax.set_title('Percentage Increase of Pollution During Event')
ax.legend()

for rects in [rects1, rects2]:
    for rect in rects:
        ax.text(rect.get_width() + 1, rect.get_y() + rect.get_height()/2,
                f"{rect.get_width():.1f}%", va='center', fontsize=10)

plt.grid(axis='x', linestyle='--', alpha=0.6)
plt.show()